spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      sms:
        host: http://dingxin.market.alicloudapi.com
#        host: https://fesms.market.alicloudapi.com
        path: /dx/sendSms
#        skin: 1
#        sign: 175622
#        appcode: b0563c23aff8428c97a54d4f7f9e28e5
        appcode: #

  application:
    name: gulimall-third-party

server:
  port: 30000